Repository opentelekomcloud-infra/delatore, pull requests merged in 2020-01, with the labels that each got.

#39 Update license
  LICENSE
Labels: documentation

#41 Separate unit- and acceptance- tests
  .travis.yml
  delatore/sources/awx_api.py
  poetry.lock
  tests/01_unit/conftest.py
  tests/01_unit/test_config.py
  tests/01_unit/test_json2md.py
  tests/01_unit/test_sources.py
  tests/02_acceptance/conftest.py
  tests/02_acceptance/test_awx_status.py
  tests/02_acceptance/test_bot.py
  tests/conftest.py
  tests/helpers.py
  tests/test_json2md.py
Labels: enhancement

#37 Parsing /status comand
  README.md
  delatore/bot/__init__.py
  delatore/bot/main.py
  delatore/bot/parsing.py
  delatore/helpers.py
  delatore/sources/awx_api.py
  poetry.lock
  tests/01_unit/test_parsing.py
  tests/02_acceptance/test_bot.py
Labels: bug, enhancement

#46 Add codecov integration
  .travis.yml
  README.md
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement

#45 Architecture/async
  delatore/__main__.py
  delatore/bot/__init__.py
  delatore/bot/main.py
  delatore/bot/parsing.py
  delatore/configuration.py
  delatore/sources/awx_api.py
  delatore/sources/base.py
  delatore/sources/http.py
  delatore/sources/influx.py
  poetry.lock
  pyproject.toml
  tests/01_unit/conftest.py
  tests/01_unit/test_parsing.py
  tests/02_acceptance/conftest.py
  tests/02_acceptance/test_awx_status.py
  tests/02_acceptance/test_bot.py
  tests/02_acceptance/test_influx.py
Labels: enhancement

#47 Change structure
  .coveragerc
  .gitignore
  .pylintrc
  .travis.yml
  delatore/__main__.py
  delatore/bot/__init__.py
  delatore/bot/main.py
  delatore/configuration.py
  delatore/helpers.py
  delatore/json2mdwn.py
  delatore/outputs/__init__.py
  delatore/outputs/telegram/__init__.py
  delatore/outputs/telegram/bot.py
  delatore/outputs/telegram/parsing.py
  delatore/sources/__init__.py
  delatore/sources/awx_api.py
  delatore/sources/base.py
  delatore/sources/http.py
  delatore/sources/influx.py
  poetry.lock
  pyproject.toml
  tests/01_unit/__init__.py
  tests/01_unit/conftest.py
  tests/01_unit/outputs/__init__.py
  tests/01_unit/outputs/conftest.py
  tests/01_unit/outputs/test_tg_commands.py
  tests/01_unit/sources/__init__.py
  tests/01_unit/sources/conftest.py
  tests/01_unit/sources/test_source_convert.py
  tests/01_unit/sources/test_sources.py
  tests/01_unit/test_sources.py
  tests/02_acceptance/__init__.py
  tests/02_acceptance/conftest.py
  tests/02_acceptance/outputs_ext/__init__.py
  tests/02_acceptance/outputs_ext/conftest.py
  tests/02_acceptance/outputs_ext/test_bot.py
  tests/02_acceptance/sources_ext/__init__.py
  tests/02_acceptance/sources_ext/conftest.py
  tests/02_acceptance/sources_ext/test_awx_status.py
  tests/02_acceptance/sources_ext/test_awx_web_hook.py
  tests/02_acceptance/sources_ext/test_influx.py
  tests/02_acceptance/test_awx_status.py
  tests/02_acceptance/test_bot.py
  tests/02_acceptance/test_influx.py
  tests/02_acceptance/test_startup.py
  tests/conftest.py
  tests/helpers.py
Labels: enhancement

#50 Architecture changes
  .coveragerc
  .gitignore
  .pylintrc
  .travis.yml
  delatore/__init__.py
  delatore/__main__.py
  delatore/bot/__init__.py
  delatore/bot/main.py
  delatore/configuration.py
  delatore/helpers.py
  delatore/json2mdwn.py
  delatore/outputs/__init__.py
  delatore/outputs/telegram/__init__.py
  delatore/outputs/telegram/bot.py
  delatore/outputs/telegram/parsing.py
  delatore/sources/__init__.py
  delatore/sources/awx_api.py
  delatore/sources/base.py
  delatore/sources/http.py
  delatore/sources/influx.py
  poetry.lock
  pyproject.toml
  requirements.txt
  tests/01_unit/__init__.py
  tests/01_unit/conftest.py
  tests/01_unit/outputs/__init__.py
  tests/01_unit/outputs/conftest.py
  tests/01_unit/outputs/test_tg_commands.py
  tests/01_unit/sources/__init__.py
  tests/01_unit/sources/conftest.py
  tests/01_unit/sources/test_source_convert.py
  tests/01_unit/sources/test_sources.py
  tests/01_unit/test_sources.py
  tests/02_acceptance/__init__.py
  tests/02_acceptance/conftest.py
  tests/02_acceptance/outputs_ext/__init__.py
  tests/02_acceptance/outputs_ext/conftest.py
  tests/02_acceptance/outputs_ext/test_bot.py
  tests/02_acceptance/sources_ext/__init__.py
  tests/02_acceptance/sources_ext/conftest.py
  tests/02_acceptance/sources_ext/test_awx_status.py
  tests/02_acceptance/sources_ext/test_awx_web_hook.py
  tests/02_acceptance/sources_ext/test_influx.py
  tests/02_acceptance/test_awx_status.py
  tests/02_acceptance/test_bot.py
  tests/02_acceptance/test_startup.py
  tests/conftest.py
  tests/helpers.py
Labels: enhancement

#53 Feature/internal config
  .pylintrc
  delatore/configuration/__init__.py
  delatore/configuration/dynamic.py
  delatore/configuration/resources/outputs.yaml
  delatore/configuration/resources/sources.yaml
  delatore/configuration/static.py
  delatore/json2mdwn.py
  delatore/outputs/telegram/bot.py
  delatore/outputs/telegram/parsing.py
  delatore/sources/awx_api.py
  delatore/sources/base.py
  delatore/sources/http.py
  delatore/sources/influx.py
  poetry.lock
  pyproject.toml
  tests/01_unit/10_general/__init__.py
  tests/01_unit/10_general/test_config.py
  tests/01_unit/10_general/test_json2md.py
  tests/01_unit/12_sources/__init__.py
  tests/01_unit/12_sources/conftest.py
  tests/01_unit/12_sources/test_source_convert.py
  tests/01_unit/12_sources/test_sources.py
  tests/01_unit/13_outputs/__init__.py
  tests/01_unit/13_outputs/conftest.py
  tests/01_unit/13_outputs/test_tg_commands.py
  tests/01_unit/conftest.py
  tests/01_unit/outputs/conftest.py
  tests/02_acceptance/20_test_startup.py
  tests/02_acceptance/21_sources_ext/__init__.py
  tests/02_acceptance/21_sources_ext/conftest.py
  tests/02_acceptance/21_sources_ext/test_awx_status.py
  tests/02_acceptance/21_sources_ext/test_awx_web_hook.py
  tests/02_acceptance/21_sources_ext/test_influx.py
  tests/02_acceptance/22_outputs_ext/__init__.py
  tests/02_acceptance/22_outputs_ext/conftest.py
  tests/02_acceptance/22_outputs_ext/test_bot.py
  tests/02_acceptance/23_integration.py
  tests/02_acceptance/conftest.py
  tests/conftest.py
Labels: bug, enhancement

#59 Move sources timings to sources.yaml
  delatore/configuration/resources/sources.yaml
  delatore/configuration/static.py
  delatore/sources/awx_api.py
  delatore/sources/base.py
  delatore/sources/http.py
  delatore/sources/influx.py
  poetry.lock
Labels: enhancement
